# This file was generated by GoReleaser. DO NOT EDIT.
class Shipyard < Formula
  desc ""
  homepage "https://shipyard.run/"
  version "0.0.24"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shipyard-run/shipyard/releases/download/v0.0.24/shipyard_0.0.24_Darwin_x86_64.tar.gz"
    sha256 "31bf1cd056013e8c276ea51b1e1e0821d2f2958d652efd22a8a0c65bd665c85c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/shipyard-run/shipyard/releases/download/v0.0.24/shipyard_0.0.24_Linux_x86_64.tar.gz"
      sha256 "acb6444591cb94db545041816b368250d70fb36274433d81261017a7785d9c82"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shipyard-run/shipyard/releases/download/v0.0.24/shipyard_0.0.24_Linux_arm64.tar.gz"
        sha256 "48ade2ea97da871e32fc36b9e26c0c49e9da632096798868568bd6f00772f78f"
      else
        url "https://github.com/shipyard-run/shipyard/releases/download/v0.0.24/shipyard_0.0.24_Linux_armv6.tar.gz"
        sha256 "5de790cf8eb5c645459445b1fb3daea87dbefe576e8dc202500b6f3b2b107137"
      end
    end
  end

  def install
    bin.install "shipyard"
  end
end
